### Import packages

In [6]:
import pandas as pd
import matplotlib.pyplot as plt

### Load dataset

In [8]:
data="C:\\Users\\Sumit Hazra\\Desktop\\Bike-rental-demand-forecasting\\data\\Cleaned_Bike_dataset.csv"
df=pd.read_csv(data,encoding='utf-8')

In [9]:
df.head()

,Rented Bike Count,Hour,Temperature(째C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(째C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day,Day,Month,Year,weekday
0,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes,12.0,1.0,2017.0,Thursday
1,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes,12.0,1.0,2017.0,Thursday
2,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,Winter,No Holiday,Yes,12.0,1.0,2017.0,Thursday
3,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes,12.0,1.0,2017.0,Thursday
4,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,Winter,No Holiday,Yes,12.0,1.0,2017.0,Thursday